// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserMicroservice.Db;

namespace UserMicroservice.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210925182518_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("UserMicroservice.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Nickname")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<int>("TotalAttendance")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(2001, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Perez",
                            Name = "Pedro",
                            Nickname = "pedro7",
                            Password = "123",
                            TotalAttendance = 0
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(2001, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Perez",
                            Name = "Maria",
                            Nickname = "maria7",
                            Password = "123",
                            TotalAttendance = 0
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(2001, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Perez",
                            Name = "Gabriela",
                            Nickname = "gabriela7",
                            Password = "123",
                            TotalAttendance = 0
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(2001, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Perez",
                            Name = "Galia",
                            Nickname = "galia7",
                            Password = "123",
                            TotalAttendance = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
